# Build on MacOS

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request
  push:
  pull_request:

  # Allow from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run build script
        run: bash build.sh

      # # Build test iOS App - Clean
      # - name: Prep Test iOS App
      #   run: xcodebuild clean -project "example/iOS Test App/iOS Test App.xcodeproj"

      # # Build test iOS App - Build
      # - name: Build Test iOS App
      #   run: xcodebuild build -project "example/iOS Test App/iOS Test App.xcodeproj" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -arch x86_64

